//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2022_hantane_randevu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hastaneadi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hastaneadi()
        {
            this.Randevu = new HashSet<Randevu>();
            this.Sehir = new HashSet<Sehir>();
        }
    
        public int hastaneId { get; set; }
        public string dokuzeylul { get; set; }
        public string mentesedevlet { get; set; }
        public string ankarahastanesi { get; set; }
        public string istanbulhastanesi { get; set; }
        public string bursahastanesi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Randevu> Randevu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sehir> Sehir { get; set; }
    }
}
