//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2022_hantane_randevu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sehir
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sehir()
        {
            this.Randevu = new HashSet<Randevu>();
        }
    
        public int sehirId { get; set; }
        public Nullable<int> hastaneId { get; set; }
        public string izmir { get; set; }
        public string mugla { get; set; }
        public string ankara { get; set; }
        public string istanbul { get; set; }
        public string bursa { get; set; }
    
        public virtual Hastaneadi Hastaneadi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Randevu> Randevu { get; set; }
    }
}
